
ANTHROPIC_API_KEY = "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"
JWT_SECRET = "ai_wellness_X7k#mP9qL2nR5vT8wY3uE6jA1cB4dF0g"
[mysql]
host     = "94.73.151.154"
database = "u1927296_olgundb"
user     = "u1927296_olgundb"
password = "Js=bY==_hQ7dB056"
port     = 3306